// @ts-ignore
import colors from "./colors.module.css";

type Dictionary<T> = Record<string, T>;

interface MapElement {
  name: string;
  color: number[];
  dark_color: number[];
  type: string;
  checked: boolean;
  stroke: number;
}

export const mapElements: Dictionary<MapElement> = {
  Sverige: {
    name: "00_sverige",
    color: colors.ground,
    dark_color: colors["dark-ground"],
    type: "ground",
    checked: true,
    stroke: 1,
  },
  "Anlagt vatten": {
    name: "01_anlagt_vatten",
    color: colors.water,
    dark_color: colors["dark-water"],
    type: "ground",
    checked: true,
    stroke: 1,
  },
  Vattendragsyta: {
    name: "02_vattendragsyta",
    color: colors.water,
    dark_color: colors["dark-water"],
    type: "ground",
    checked: true,
    stroke: 1,
  },
  Sjö: {
    name: "03_sjo",
    color: colors.water,
    dark_color: colors["dark-water"],
    type: "ground",
    checked: true,
    stroke: 1,
  },
  Glaciär: {
    name: "04_glaciar",
    color: colors.glacier,
    dark_color: colors["dark-glacier"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Kalfjäll: {
    name: "05_kalfjall",
    color: colors["open-mountain"],
    dark_color: colors["dark-open-mountain"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Fjällbjörkskog: {
    name: "06_fjallbjorkskog",
    color: colors["mountain-birch"],
    dark_color: colors["dark-mountain-birch"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Lövskog: {
    name: "08_lovskog",
    color: colors["leaf-fores"],
    dark_color: colors["dark-leaf-fores"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Åker: {
    name: "09_aker",
    color: colors.field,
    dark_color: colors["dark-field"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Fruktodling: {
    name: "10_fruktodling",
    color: colors["fruit-farm"],
    dark_color: colors["dark-fruit-farm"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  "Öppen mark": {
    name: "11_oppen_mark",
    color: colors["open-ground"],
    dark_color: colors["dark-open-ground"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  "Hög bebyggelse": {
    name: "12_hog_bebygelse",
    color: colors["city-dense"],
    dark_color: colors["dark-city-dense"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  "Låg bebyggelse": {
    name: "13_lag_bebygelse",
    color: colors["city-sparse"],
    dark_color: colors["dark-city-sparse"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  "Sluten bebyggelse": {
    name: "14_sluten_bebygelse",
    color: colors["city-closed"],
    dark_color: colors["dark-city-closed"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  "Industri- och handelsbebyggelse": {
    name: "15_industri_handel",
    color: colors["city-industry"],
    dark_color: colors["dark-city-industry"],
    type: "ground",
    checked: true,
    stroke: 0,
  },
  Motorväg: {
    name: "01_motorvag",
    color: colors.motorway,
    dark_color: colors["dark-motorway"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Motortrafikled: {
    name: "02_motortrafikled",
    color: colors["motor-trafic-route"],
    dark_color: colors["dark-motor-trafic-route"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Mötesfri väg": {
    name: "03_motesfri_vag",
    color: colors["overall-link"],
    dark_color: colors["dark-overall-link"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Landsväg: {
    name: "04_landsvag",
    color: colors["country-road"],
    dark_color: colors["dark-country-road"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Landsväg liten": {
    name: "05_landsvag_liten",
    color: colors["country-road-small"],
    dark_color: colors["dark-country-road-small"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Småväg: {
    name: "06_smavag",
    color: colors["main-street"],
    dark_color: colors["dark-main-street"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Småväg enkel standard": {
    name: "07_smavag_enkel_standard",
    color: colors["local-street-large"],
    dark_color: colors["dark-local-street-large"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Övergripande länk": {
    name: "08_overgripande_lank",
    color: colors["local-street-small"],
    dark_color: colors["dark-local-street-small"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Huvudgata: {
    name: "09_huvudgata",
    color: colors["meeting-free-road"],
    dark_color: colors["dark-meeting-free-road"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Lokalgata stor": {
    name: "10_lokalgata_stor",
    color: colors["small-road"],
    dark_color: colors["dark-small-road"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Lokalgata liten": {
    name: "11_lokalgata_liten",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Parkväg: {
    name: "01_parkvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Cykelväg: {
    name: "02_cykelvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Gångstig: {
    name: "03_gangstig",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Elljusspår: {
    name: "04_elljusspar",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Traktorväg: {
    name: "05_traktorvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Vandringsled: {
    name: "06_vandringsled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Vandrings- och vinterled": {
    name: "07_vandrings_vinterled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Vinterled: {
    name: "08_vinterled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Lämplig färdväg": {
    name: "01_lamplig_fardvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Rennäringsled: {
    name: "02_rennaringsled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Fångstarm till led": {
    name: "03_fangstarm_till_led",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Roddled: {
    name: "04_roddled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Svårorienterad gångstig": {
    name: "05_svarorienterad_gangstig",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },

  Skidspår: {
    name: "06_skidspar",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Båtdrag: {
    name: "07_batdrag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  "Trafikerad båtled": {
    name: "08_trafikerad_batled",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Järnväg: {
    name: "01_jarnvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Museijärnväg: {
    name: "02_museijarnvag",
    color: colors["small-road-simple"],
    dark_color: colors["dark-small-road-simple"],
    type: "communication",
    checked: true,
    stroke: 0,
  },
  Bostad: {
    name: "01_bostad",
    color: colors["residence-building"],
    dark_color: colors["dark-residence-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Industri: {
    name: "02_industri",
    color: colors["economy-building"],
    dark_color: colors["dark-economy-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Samhällsfunktion: {
    name: "03_samhallsfunktion",
    color: colors["complement-building"],
    dark_color: colors["dark-complement-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Verksamhet: {
    name: "04_verksamhet",
    color: colors["community-building"],
    dark_color: colors["dark-community-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Ekonomibyggnad: {
    name: "05_ekonomibyggnad",
    color: colors["economy-building"],
    dark_color: colors["dark-economy-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Komplementbyggnad: {
    name: "06_komplementbyggnad",
    color: colors["operation-building"],
    dark_color: colors["dark-operation-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  "Övrig byggnad": {
    name: "07_ovrig",
    color: colors["other-building"],
    dark_color: colors["dark-other-building"],
    type: "construction",
    checked: true,
    stroke: 0,
  },
  Temperatur: {
    name: "01_temperatur",
    color: colors["other-building"],
    dark_color: colors["dark-other-building"],
    type: "data",
    checked: false,
    stroke: 0,
  },
};
