export const ground: { [index: string]: any } = {
  "Granskog/Mark": "00_sverige",
  "Anlagt vatten": "01_anlagt_vatten",
  Vattendragsyta: "02_vattendragsyta",
  Sjö: "03_sjo",
  Glaciär: "04_glaciar",
  Kalfjäll: "05_kalfjall",
  Fjällbjörkskog: "06_fjallbjorkskog",
  Lövskog: "08_lovskog",
  Åker: "09_aker",
  Fruktodling: "10_fruktodling",
  "Öppen mark": "11_oppen_mark",
  "Hög bebyggelse": "12_hog_bebygelse",
  "Låg bebyggelse": "13_lag_bebygelse",
  "Sluten bebyggelse": "14_sluten_bebygelse",
  "Industri- och handelsbebyggelse": "15_industri_handel",
};

export const road: { [index: string]: any } = {
  Motorväg: "01_motorvag",
  Motortrafikled: "02_motortrafikled",
  "Mötesfri väg": "03_motesfri_vag",
  Landsväg: "04_landsvag",
  "Landsväg liten": "05_landsvag_liten",
  Småväg: "06_smavag",
  "Småväg enkel standard": "07_smavag_enkel_standard",
  "Övergripande länk": "08_overgripande_lank",
  Huvudgata: "09_huvudgata",
  "Lokalgata stor": "10_lokalgata_stor",
  "Lokalgata liten": "11_lokalgata_liten",
  Parkväg: "01_parkvag",
  Cykelväg: "02_cykelvag",
  Gångstig: "03_gangstig",
  Elljusspår: "04_elljusspar",
  Traktorväg: "05_traktorvag",
  Vandringsled: "06_vandringsled",
  "Vandrings- och vinterled": "07_vandrings_vinterled",
  Vinterled: "08_vinterled",
  "Lämplig färdväg": "01_lamplig_fardvag",
  Rennäringsled: "02_rennaringsled",
  "Fångstarm till led": "03_fangstarm_till_led",
  Roddled: "04_roddled",
  "Svårorienterad gångstig": "05_svarorienterad_gangstig",
  Skidspår: "06_skidspar",
  Båtdrag: "07_batdrag",
  "Trafikerad båtled": "08_trafikerad_batled",
  Järnväg: "01_jarnvag",
  Museijärnväg: "02_museijarnvag",
};

export const construction: { [index: string]: any } = {
  Bostad: "01_bostad",
  Industri: "02_industri",
  Samhällsfunktion: "03_samhallsfunktion",
  Verksamhet: "04_verksamhet",
  Ekonomibyggnad: "05_ekonomibyggnad",
  Komplementbyggnad: "06_komplementbyggnad",
  "Övrig byggnad": "07_ovrig",
};
